/**
 * generated-holding-core — the construction site's company and its projects,
 * invented here.
 *
 * B36 Block 2, the re-audit of 2026-08-23 evening. The first answer made the
 * WORKFORCE synthetic and stopped there; the auditor read on and found that
 * `db/seed/build-seed.ts:121` still ran `db/seed/20260711_holding_core.sql`,
 * which carries the holding itself:
 *
 *     'dxb-global', 'DXB Global', 'AI-native technology consultancy holding: …'
 *     'dxb-global-os', 'DXB Global OS', 'The holding''s own operating system — …',
 *     'HOLDING-OS-MASTER-PLAN/MASTER_PLAN.md'
 *
 * — the company's real name, its real mission, its first project's real name and
 * purpose, and links pointing at real documents in this repository. The approved
 * plan says the opposite in as many words: *"a complete but entirely fictional
 * holding … and not one row of his"* (PLAN.md:221-224). And the file was not the
 * whole of it: the migration chain seeds a SECOND project, `revenue-discovery`,
 * with its own authored purpose and its own real document link, and two later
 * migrations write the Turkish halves of both.
 *
 * WHAT MAY STAY AND WHAT MAY NOT — the CEO's own line, 2026-08-23:
 * *"Testlerin ihtiyaç duyduğu yapısal anahtarlar kalabilir; şirket adı, görev
 * metni, proje adı/amacı ve gerçek dosya bağlantıları kopyalanamaz."*
 *
 *   stays   the SLUGS. They are not decoration: `dxb-global` is read by four
 *           migrations and by a live database function
 *           (`20260712008000_hr_factory_fns_e54b.sql:61`), and `dxb-global-os`
 *           is read by `packages/orchestrator/src/intent-intake.ts:23` and by
 *           `tests/r23/unified-constitution.test.ts:142`. A slug is a key.
 *           So are the owner, the company binding and the four memory-store
 *           identities the CEO's Bellek page joins on by name.
 *   never   the company's name and mission · a project's name and purpose in
 *           either language · `strategy_link` and `links`, which point at real
 *           documents · the store notes written for the library catalogue.
 *
 * Deterministic, like the workforce: the same slug yields the same text on every
 * machine and on every run, so re-running the seed writes nothing new.
 */
import { hash, pick, revision } from "./generated-workforce.ts";

/** The one company key the migration chain and a live database function read. */
export const HOLDING_SLUG = "dxb-global";
/** The one project key the orchestrator and the r23 suite read. */
export const HOLDING_PROJECT_SLUG = "dxb-global-os";

/**
 * The four memory stores, by name. These are IDENTITIES, not prose: the CEO's
 * Bellek page joins `library_items(kind='memory_source')` by name for its
 * inventory cards, and `tests/phase8/memory-store-labels.test.ts` holds the same
 * four names. What was authored — the catalogue note beside each — is generated.
 */
export const MEMORY_STORES = ["pgvector", "graphify", "obsidian", "notebook"] as const;

const HOUSE = ["Fairwind", "Northgate", "Bluerock", "Stonebridge", "Clearwater", "Highfield"] as const;

export interface CompanyFiction {
  name: string;
  mission: string;
}

/** The holding the construction site works on. It does not exist. */
export function companyFictionFor(slug: string): CompanyFiction {
  const house = pick(HOUSE, slug, "house");
  return {
    name: `${house} Fixture Holding`,
    mission:
      `A holding that exists only inside the construction site's own database. It has no owners, ` +
      `no money, no customers and no history; it is here so that the machinery built around a ` +
      `company has something company-shaped to run against. Generated by db/seed/build-seed.ts, ` +
      `revision ${revision(slug)} — nothing in this record describes a real business.`,
  };
}

// Eight by eight, so two projects on the same engine rarely wear the same
// words. English and Turkish are indexed by the SAME two salts, so a row's
// two names are a pair rather than two unrelated inventions.
const PROJ_EN = ["Blue Harbour", "Long Bridge", "North Field", "Still Water", "Open Yard", "Grey Gate", "Low Meadow", "Old Quarry"] as const;
const PROJ_TR = ["Mavi Liman", "Uzun Köprü", "Kuzey Tarla", "Durgun Su", "Açık Avlu", "Gri Kapı", "Alçak Çayır", "Eski Ocak"] as const;
const KIND_EN = ["Programme", "Workstream", "Track", "Line", "Build", "Yard", "Bench", "Round"] as const;
const KIND_TR = ["Programı", "İş Kolu", "İzi", "Hattı", "Yapısı", "Sahası", "Tezgâhı", "Turu"] as const;

export interface ProjectFiction {
  name: string;
  name_tr: string;
  purpose: string;
  purpose_tr: string;
  strategy_link: string;
  links: string;
}

/**
 * A project on that holding. The name is INVENTED rather than derived from the
 * slug: `dxb-global-os` title-cased would still be his project's name, and the
 * CEO's line forbids exactly that.
 *
 * `strategy_link` and `links` keep the SHAPE the CEO's project page reads —
 * repos, docs, deploys, versions — and carry nothing that resolves to a real
 * file. The scheme `build-fixture://` is not a path on any disk.
 */
export function projectFictionFor(slug: string): ProjectFiction {
  const en = `${pick(PROJ_EN, slug, "proj")} ${pick(KIND_EN, slug, "kind")}`;
  const i = hash(`proj:${slug}`) % PROJ_TR.length;
  const j = hash(`kind:${slug}`) % KIND_TR.length;
  const tr = `${PROJ_TR[i]} ${KIND_TR[j]}`;
  const rev = revision(slug);
  return {
    name: en,
    name_tr: tr,
    purpose:
      `A generated project on the construction site's fictional holding, filed under the key ` +
      `\`${slug}\`. It exists so that the work engine, the claim path and the project surface have ` +
      `a real row to hang on; no work described here was ever planned, funded or done. Generated ` +
      `by db/seed/build-seed.ts, revision ${rev}.`,
    purpose_tr:
      `İnşaat alanının kurgusal holdingi üzerinde üretilmiş bir proje; \`${slug}\` anahtarıyla ` +
      `kayıtlı. İş motorunun, görev alma yolunun ve proje ekranının tutunacağı gerçek bir satır ` +
      `olsun diye vardır; burada anlatılan hiçbir iş planlanmadı, bütçelenmedi ve yapılmadı. ` +
      `db/seed/build-seed.ts tarafından üretildi, sürüm ${rev}.`,
    strategy_link: `build-fixture://charter/${slug}`,
    links: JSON.stringify({
      repos: [`build-fixture/${slug}`],
      docs: [`build-fixture/${slug}/charter`, `build-fixture/${slug}/notes`],
      deploys: [],
      versions: ["v0-fixture"],
    }),
  };
}

/** The catalogue note beside a memory store — generated, never the authored one. */
export function storeNoteFor(name: string): string {
  return (
    `Generated fixture entry for the '${name}' store on the construction engine. It records that ` +
    `the store exists so the inventory has something to count; it describes no real composition ` +
    `and no real content. Revision ${revision(name)}.`
  );
}
